### PR TITLE
Fix exit error check

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by oleorhagen** [comment]
Check https://s3.console.aws.amazon.com/s3/buckets/mender?region=us-east-1&prefix=temp/&showversions=false if you don't believe me...

**Comment by oleorhagen** [comment]
I'm guessing this could be moved to use the regular `aws s3 cp` command instead also? :thinking:

**Review by kacf — APPROVED** [review]
> This has been failing in silence for a very long time.

Yes, but it hasn't been executed, AFAIK. 🙂

> I'm guessing this could be moved to use the regular `aws s3 cp` command instead also?

Whichever is recommended to use by Amazon I suppose.

**Comment by kacf** [comment]
Old, please reopen if necessary.

**Pull request closed without merging**
